appointment/urls.py
from . import views
from django.urls import path
from .views import appointment_template_view, HomeTemplateView,\
                    ManageAppointmentTemplateView
from django.contrib.auth.decorators import login_required
from django.urls import path, include


urlpatterns = [
     path("", HomeTemplateView.as_view(), name="home"),
     path("make-an-appointment/", views.appointment_template_view, name="appointment"),
     path("manage-appointments/", login_required(views.ManageAppointmentTemplateView.as_view()), name="manage"),
     path("login/", views.login_request, name="login"),
     path("register", views.register_request, name="register"),
     path('logout/', views.logout_view, name='logout'),
     path('delete/<int:appointment_id>', views.delete_appointment,
          name='delete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("appointment.urls")),
    path('accounts/', include('allauth.urls')),
    path('captcha/', include('captcha.urls')),
]

appointment/models.py
from django.db import models
from django.http import request
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField


TIME_SLOTS = (
    ('0', '15:30 - 15:45'),
    ('1', '15:45 - 16:00'),
    ('2', '16:00 - 16:15'),
    ('3', '16:15 - 16:30'),
    ('4', '16:30 - 16:45'),
    ('5', '16:45 - 17:00'),
)


class Teacher(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


# Create your models here.
class Appointment(models.Model):
    parent_name = models.CharField(max_length=50)
    child_name = models.CharField(max_length=50)
    teacher = models.ForeignKey(Teacher, on_delete=models.SET_NULL,
                                blank=False, null=True)
    class_name = models.CharField(max_length=50)
    date = models.DateField()
    time = models.CharField(max_length=80, choices=TIME_SLOTS, default='0')
    email = models.EmailField(max_length=50)
    comments = models.TextField(blank=True)
    accepted = models.BooleanField(default=False)

    """Good practice to add a magic method that returns a string
       representation of an object.
    """
    def __str__(self):
        return f"Appointment for {self.child_name} in {self.class_name}\
            with {self.teacher}"

send_mail/models.py
from django.db import models

# Create your models here.

appointment/forms.py
from django import forms
from django.forms import ModelForm
from .models import Appointment, Teacher
from captcha.fields import CaptchaField
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Date Picker for the Appointment form
class DateInput(forms.DateInput):
    input_type = 'date'


# Appointment form
class AppointmentCreationForm(forms.ModelForm):
    captcha = CaptchaField(
        label='Please enter the characters in the image',
        required=True,
        error_messages={'invalid': 'CAPTCHA invalid. Please try again.'}
    )

    class Meta:
        model = Appointment
        fields = '__all__'
        widgets = {
            'date': DateInput(),
        }
        exclude = ('accepted', 'accepted_date')


# Admin Signup form
class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

appointment/views.py
from django.http.response import HttpResponseRedirect
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.base import TemplateView
from django.views.generic import ListView
from django.core.mail import EmailMessage, message, send_mail
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from .models import Appointment
from .forms import AppointmentCreationForm, NewUserForm
from django.template import Context
from django.template.loader import render_to_string, get_template
import datetime
from django.urls import reverse
from captcha.fields import CaptchaField

# Views Start Here


class HomeTemplateView(TemplateView):
    template_name = "index.html"

    def post(self, request):
        name = request.POST.get("name")
        email = request.POST.get("email")
        message = request.POST.get("message")


# CREATE APPOINTMENT
def appointment_template_view(request):
    form = AppointmentCreationForm()
    if request.method == 'POST':
        form = AppointmentCreationForm(request.POST)
        if form.is_valid():
            form.save()
            human = True
            messages.success(request, f"Thanks for making an appointment, we\
                will email you soon to confirm.")
            return redirect('appointment')
        else:
            messages.error(request, f"CAPTCHA Invalid. Letters are case\
                sensitive. Please try again.")
    return render(request, 'appointment.html', {'form': form})


# READ AND UPDATE APPOINTMENT
class ManageAppointmentTemplateView(ListView):
    template_name = "manage-appointments.html"
    model = Appointment
    context_object_name = "appointments"
    login_required = True
    paginate_by = 3

    def post(self, request):
        date = request.POST.get("date")
        appointment_id = request.POST.get("appointment-id")
        appointment = Appointment.objects.get(id=appointment_id)
        appointment.accepted = True
        appointment.accepted_date = datetime.datetime.now()
        appointment.save()
        email = appointment.email

        # Send Email
        send_mail(
            'Your appointment confirmed at Fairchild School',
            'Hello, your appointment has been confirmed. See you soon.',
            'krishantest7@gmail.com',
            [email],
            )

        messages.add_message(request, messages.SUCCESS,
                             f"You accepted the appointment\
                             of {appointment.parent_name}")
        return HttpResponseRedirect(request.path)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        appointments = Appointment.objects.all()
        context.update({
            "title": "Manage Appointments"
        })
        return context


# DELETE APPOINTMENT
def delete_appointment(request, appointment_id):
    appointment = get_object_or_404(Appointment, pk=appointment_id)
    appointment.delete()
    messages.add_message(request, messages.SUCCESS,
                         f"The appointment has been deleted.")
    return redirect('manage')


# AJAX
def load_teacher(request):
    teacher_id = request.GET.get('teacher_id')


# LOGIN PAGE
def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                # messages.info(request, f"You are now logged in as {username}.")
                return redirect("manage")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    return render(request=request, template_name="login.html",
                  context={"login_form": form})


# LOG OUT MESSAGE
def logout_view(request):
    logout(request)
    messages.error(request, "Invalid username or password.")
    return HttpResponseRedirect(request.path)


# ADMIN SIGN UP
def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("manage")
        messages.error(request, "Unsuccessful registration. Invalid\
                       information.")
    form = NewUserForm()
    return render(request=request, template_name="signup.html",
                  context={"register_form": form})

send_mail/views.py
from django.shortcuts import render

# Create your views here.

templates/appointment.html
{% extends 'base.html' %}

{% block content %}



<div class="container-fluid px-1 py-5 mx-auto appointment-background">
    <div class="row d-flex justify-content-center">
        <div class="col-xl-7 col-lg-8 col-md-9 col-11 text-center appointment-text">
            <h3>
                Book an appointment
            </h3>
            <p class="blue-text">Use the following form to request an appointment..</p>
            <div class="appointmentcard">
                <form method="post" id="appointmentForm">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Submit">
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="The Fairchild School Appointment App for Parents and Teachers.">
    <meta name="keywords" content="school, appointment, parent-teacher, fairchild school">
    <meta name="author" content="Krishan Gharu for Code Institute Portfolio Project 4">
    <title>Fairchild School App</title>
    {% comment %} Bootstrap CSS via jsDelivr {% endcomment %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    {% comment %} Font Awesome {% endcomment %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    {% comment %} Custom CSS {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% comment %} To get your favicon displaying in Production {% endcomment %}
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="{% url 'home' %}">Fairchild School App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'appointment' %}">Make Appointment</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'manage' %}">Teacher Admin</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_logout' %}">Sign Out</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    {% if messages %}
    {% for message in messages %}
        {% with message.level as level %}
            {% if level == 40 %}
                <div id="alert" class="alert alert-warning" role="alert">
                <div class="card-body">
                <div class="card-title">{{message}}</div>
                </div>
                </div> 
            {% else %}
                <div id="alert" class="alert alert-success" role="alert">
                <div class="card-body">
                <div class="card-title">{{message}}</div>
                </div>
                </div> 
            {% endif %}
        {% endwith %}
      {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock content %}

    <footer class="footer mt-auto py-3">
      <a href="https://www.linkedin.com/in/krishang/" target="_blank" rel="noopener" aria-label="Visit the website developer's Linkedin page">
      <p class="m-0 text-center text-black">&#169; Krishan Gharu <span id="copyright"></span></p>
      </a>
    </footer>
    {% comment %} Bootstrap JS via jsDelivr {% endcomment %}
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <script src="{% static 'js/script.js' %}" type="text/javascript"></script>
    <!-- Custom script for copyright year. Needs to be loaded last -->
    <script>
      $("#copyright").text(new Date().getFullYear());
    </script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block cta %}
{% block content %}
<div class="mask rgba-gradient d-flex justify-content-center align-items-center hero-img">
  <div class="container">
    <div class="row">
      <div class="homepage-content col-md-6 white-text text-center text-md-center mt-xl-5 mb-5 card wow img-fluid animated fadeIn" data-wow-delay="0.3s">
        <h2 class="h2-responsive font-weight-bold mt-sm-3">Parent Teacher Consultation App</h2>
        <a href="{% url 'appointment' %}" class="btn btn-light btn-lg action-button">Book an appointment</a>
      </div>
    </div>
  </div>
</div>
{% endblock content %}  
{% endblock cta %}

templates/manage-appointments.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid px-1 py-5 mx-auto manage-background">
  <div class="col-12 text-center mt-4 mb-4">
      <h3>
        Manage appointments
      </h3>
  </div>
  <div class="row d-flex justify-content-center">
  {% for app in appointments %}
  <div class="col-lg-3">
      <div class="card card-margin">
          <div class="card-header no-border">
            <p class="card-title">Parent: {{app.parent_name}}</p>
          </div>
          <div class="card-header no-border">
            <p class="card-title">Teacher: {{app.teacher}}</p>
          </div> 
          <div class="card-header no-border">
            <p class="card-title">Child: {{app.child_name}}</p>
          </div>
          <div class="card-body pt-0">
              <div class="widget-49">
                  <div class="widget-49-title-wrapper">
                      <div class="widget-49-date-primary">
                          <span class="widget-49-date-day">{{app.date|date:"d"}}</span>
                          <span class="widget-49-date-month">{{app.date|date:"M"}}</span>
                      </div>
                      <div class="widget-49-meeting-info">
                        <span class="widget-49-pro-title">{{app.get_time_display}}</span>
                        <span class="widget-49-pro-title">{{app.email}}</span>
                        <span class="widget-49-meeting-time">{{app.phone}}</span>
                      </div>
                  </div>
                  <div class="widget-49-meeting-points">
                      <span>{{app.request}}</span>
                  </div>
                  <hr class="w-100">
                  {% if app.accepted == False %}
                  <form method="POST" action="{% url 'manage' %}">
                    {% csrf_token %}
                    <div class="form-group manage-cards">
                        <input class="manage-id" name="appointment-id" value="{{app.id}}">
                        <input class="btn-block btn form-control" type="submit" value="Accept">
                    </div>
                  </form>
                  {% else %}
                  <div class="widget-49-meeting-points">
                    <span class="badge badge-success">Appointment Confirmed</span>
                    <div><br></div>
                  </div>
                  {% endif %}
                  <a class="btn btn-danger" role="button" data-toggle="modal" data-target="#modal-{{ app.id }}">Delete</a>
                  <!-- Delete Modal -->
                  <div id="modal-{{ app.id }}" class="modal fade" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-hidden="true">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title">Delete Appointment?</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                        <p>Are you sure you want to delete this appointment?</p>
                        <p>This action cannot be undone.</p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                          <a href="{% url 'delete' app.id %}" class="btn btn-primary">Delete</a>
                        </div>
                      </div>
                    </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
  {% endfor %}
  </div>
  {% if is_paginated %}
  <div class="wrapper">
      <nav aria-label="Page navigation example">
          <ul class="pagination">
              {% if page_obj.has_previous %}
              <li class="page-item"><a class="page-link" href="?page={{page_obj.prebious_page_number}}">Previous</a></li>
              {% endif %}
              {% for number in page_obj.paginator.page_range %}
              <li class="page-item"><a class="page-link" href="?page={{number}}">{{number}}</a></li>
              {% endfor %}
              {% if page_obj.has_next %}
              <li class="page-item"><a class="page-link" href="?page={{page_obj.prebious_page_number}}">Next</a></li>
              {% endif %}
          </ul>
      </nav>
  </div>
  {% endif %}
</div>
{% endblock content %}